import { LegalLayout, Section } from "@/components/legal/LegalLayout";
import { COMPANY } from "@/config/legal";

export default function SecurityPage() {
  return (
    <LegalLayout
      title="Security"
      description="How ClawOps protects your account, business data, uploaded files, and team access."
    >
      <p>
        Security is built into how ClawOps stores and serves your data. This page summarises the
        controls in place in plain language.
      </p>

      <Section heading="Data isolation">
        <p>
          Every record is tied to an owner account and protected by database row-level security
          policies enforced by the database itself, not just the app. One customer cannot read or
          modify another customer's data even if a client request is manipulated.
        </p>
      </Section>

      <Section heading="Encryption">
        <p>
          All traffic is served over HTTPS/TLS. Data at rest is stored on managed, encrypted cloud
          infrastructure. Passwords are salted and hashed by our authentication provider — we never
          see them.
        </p>
      </Section>

      <Section heading="Files and photos">
        <p>
          Receipts, location photos, and collection verification photos are stored in private
          buckets. They are only reachable through short-lived signed links generated for the
          authorised user; the underlying files are not publicly addressable.
        </p>
      </Section>

      <Section heading="Access control">
        <p>
          Team members receive only the permissions the owner grants — per module, with separate
          controls for viewing and managing. Roles are stored separately from profiles and checked
          server-side, so permissions cannot be escalated from the browser.
        </p>
      </Section>

      <Section heading="Payments">
        <p>
          Card data is collected and stored by Stripe, a PCI-DSS Level 1 service provider. ClawOps
          never receives full card numbers.
        </p>
      </Section>

      <Section heading="Public links">
        <p>
          Owner portal links and machine issue-report pages are intentionally accessible without a
          login. They expose only the specific location or machine they reference, are read-only
          (aside from submitting an issue report), and can be disabled or regenerated by the owner
          at any time.
        </p>
      </Section>

      <Section heading="Monitoring and updates">
        <p>
          Dependencies and database access rules are reviewed regularly with automated security
          scanning, and fixes are deployed continuously.
        </p>
      </Section>

      <Section heading="Reporting a vulnerability">
        <p>
          Email {COMPANY.securityEmail} with details and reproduction steps. We ask that you avoid
          accessing other customers' data, give us a reasonable window to remediate, and refrain
          from public disclosure until a fix is released. We do not pursue legal action against
          good-faith researchers who follow these guidelines.
        </p>
      </Section>
    </LegalLayout>
  );
}
