import { Link } from "react-router-dom";
import { LegalLayout, Section } from "@/components/legal/LegalLayout";
import { COMPANY } from "@/config/legal";

export default function Terms() {
  return (
    <LegalLayout
      title="Terms of Service"
      description="The terms governing your use of the ClawOps claw machine operations platform, including subscriptions, trials, and acceptable use."
    >
      <p>
        These Terms of Service ("Terms") are a binding agreement between {COMPANY.displayName} ("we",
        "us", "ClawOps") and the individual or business that creates an account ("you", "Customer").
        By creating an account, checking the acceptance box, or using the ClawOps service (the
        "Service"), you agree to these Terms. If you are accepting on behalf of a company, you
        represent that you are authorized to bind that company.
      </p>

      <Section heading="1. The Service">
        <p>
          ClawOps is a web-based operations platform for amusement and claw machine operators. It
          provides location, machine, revenue, inventory, maintenance, mileage, lead, team, and
          reporting tools. We may add, change, or remove features over time. We do not guarantee any
          particular feature will remain available.
        </p>
      </Section>

      <Section heading="2. Eligibility and accounts">
        <p>
          You must be at least 18 years old and able to form a binding contract. You are responsible
          for the accuracy of your account information, for keeping your credentials confidential,
          and for all activity under your account, including activity by team members you invite.
          Notify us at {COMPANY.supportEmail} if you suspect unauthorized access.
        </p>
      </Section>

      <Section heading="3. Free trial">
        <p>
          New accounts may start a 7-day free trial. A valid payment method is required to activate
          the trial. Unless you cancel before the trial ends, your subscription begins automatically
          and the payment method on file is charged the then-current subscription price. Trials are
          limited to one per customer and may not be combined with other offers. We may grant
          complimentary access to selected accounts at our discretion; complimentary access may be
          modified or ended at any time.
        </p>
      </Section>

      <Section heading="4. Subscriptions, billing, and auto-renewal">
        <ul className="list-disc space-y-2 pl-6">
          <li>
            Subscriptions are billed in advance on a monthly or annual basis through our payment
            processor, Stripe. We do not store your full card details.
          </li>
          <li>
            Subscriptions renew automatically at the end of each billing period until cancelled.
          </li>
          <li>
            You may cancel at any time from Settings. Cancellation takes effect at the end of the
            current paid period; access continues until then.
          </li>
          <li>
            We may change prices with at least 30 days' notice by email or in-app. Continued use
            after the change takes effect is acceptance of the new price.
          </li>
          <li>
            You are responsible for any applicable taxes. Failed payments may result in suspension
            of access.
          </li>
        </ul>
        <p>
          See the <Link to="/legal/refunds" className="text-primary hover:underline">Billing &amp; Refund Policy</Link> for details.
        </p>
      </Section>

      <Section heading="5. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>use the Service to violate any law or regulation, including gaming, amusement device, sweepstakes, tax, or consumer protection rules applicable to your operation;</li>
          <li>upload content that is unlawful, infringing, defamatory, or contains malware;</li>
          <li>attempt to access data belonging to other customers, probe or bypass security controls, or reverse engineer the Service;</li>
          <li>resell, sublicense, or share access outside your own team seats;</li>
          <li>use automated means to scrape or overload the Service.</li>
        </ul>
        <p>
          You are solely responsible for confirming that your machines, prize values, payouts, and
          location agreements comply with the laws where you operate. ClawOps does not provide
          legal, tax, or accounting advice, and reports generated by the Service are informational
          only.
        </p>
      </Section>

      <Section heading="6. Your data">
        <p>
          You retain all rights to the data you enter into the Service ("Customer Data"). You grant
          us a limited license to host, process, transmit, and display Customer Data solely to
          provide and support the Service, and to create aggregated, de-identified statistics that
          do not identify you or your locations. Our handling of personal information is described
          in the <Link to="/legal/privacy" className="text-primary hover:underline">Privacy Policy</Link>. Business customers may also
          rely on our <Link to="/legal/dpa" className="text-primary hover:underline">Data Processing Addendum</Link>.
        </p>
      </Section>

      <Section heading="7. Team members and end users">
        <p>
          If you invite team members, you are responsible for their use of the Service, for
          assigning appropriate permissions, and for any personal information you upload about them
          or about your location contacts. You confirm you have the right to provide that
          information to us.
        </p>
      </Section>

      <Section heading="8. Third-party services">
        <p>
          The Service integrates with third parties such as Stripe (payments), Resend (email),
          mapping and routing providers, and optional telemetry providers. Your use of those
          services is governed by their own terms. We are not responsible for third-party outages,
          data, or actions.
        </p>
      </Section>

      <Section heading="9. Availability and support">
        <p>
          We aim for high availability but the Service is provided without any uptime commitment.
          We may perform maintenance, and we may suspend the Service to address security or legal
          issues. Support is provided by email at {COMPANY.supportEmail} during normal business
          days.
        </p>
      </Section>

      <Section heading="10. Intellectual property">
        <p>
          The Service, including its software, design, and documentation, is owned by us and
          protected by intellectual property laws. We grant you a non-exclusive, non-transferable
          right to use the Service during your subscription. Feedback you send us may be used
          without restriction or compensation.
        </p>
      </Section>

      <Section heading="11. Termination">
        <p>
          You may stop using the Service and delete your account at any time from Settings. We may
          suspend or terminate your account for material breach of these Terms, non-payment, or
          unlawful use, generally after notice and an opportunity to cure where practical. On
          termination, your right to use the Service ends and your data may be deleted after a
          reasonable retention period. Export your data before terminating.
        </p>
      </Section>

      <Section heading="12. Disclaimers">
        <p className="uppercase text-xs tracking-wide text-muted-foreground">
          The Service is provided "as is" and "as available" without warranties of any kind, express
          or implied, including merchantability, fitness for a particular purpose, and
          non-infringement. We do not warrant that the Service will be uninterrupted, error free, or
          that calculations, mileage estimates, or reports will be accurate for tax or legal
          purposes.
        </p>
      </Section>

      <Section heading="13. Limitation of liability">
        <p className="uppercase text-xs tracking-wide text-muted-foreground">
          To the maximum extent permitted by law, neither party is liable for indirect, incidental,
          special, consequential, or punitive damages, or for lost profits, revenue, or data. Our
          total aggregate liability arising out of or relating to the Service will not exceed the
          amounts you paid us in the twelve months before the event giving rise to the claim.
        </p>
      </Section>

      <Section heading="14. Indemnity">
        <p>
          You will defend and indemnify us against third-party claims arising from your Customer
          Data, your operation of machines and locations, or your violation of these Terms or
          applicable law.
        </p>
      </Section>

      <Section heading="15. Governing law and disputes">
        <p>
          These Terms are governed by the laws of {COMPANY.governingLaw}, without regard to conflict
          of law rules. The parties will first attempt to resolve disputes informally by contacting{" "}
          {COMPANY.supportEmail}. Any unresolved dispute will be brought exclusively in the state or
          federal courts located in that jurisdiction, and each party consents to that venue.
        </p>
      </Section>

      <Section heading="16. Changes to these Terms">
        <p>
          We may update these Terms. Material changes will be announced in-app or by email, and the
          version and effective date at the top of this page will change. Continued use after the
          effective date means you accept the updated Terms. You may be asked to re-accept them when
          you next sign in.
        </p>
      </Section>

      <Section heading="17. Contact">
        <p>
          {COMPANY.legalName} (DBA {COMPANY.dba}) · {COMPANY.supportEmail} · {COMPANY.website}
          <br />
          {COMPANY.mailingAddress}
        </p>
      </Section>
    </LegalLayout>
  );
}
