import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { useToast } from "@/hooks/use-toast"
import { FileText, Download } from "lucide-react"
import html2pdf from "html2pdf.js"

interface FormData {
  [key: string]: string
}

export default function Documents() {
  const { toast } = useToast()
  const [formData, setFormData] = useState<FormData>({})
  const [paymentType, setPaymentType] = useState<"percentage" | "flat">("percentage")

  const locationAgreementFields = [
    "Agreement Date",
    "Provider Name", 
    "Provider Address",
    "Provider Contact Info",
    "Business Name",
    "Business Address", 
    "Business Contact Info",
    "Start Date",
    "End Date",
    "Payment Method",
    "Notice Period (Hours/Days)"
  ]

  const handleFormChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
  }

  const handleDownloadPDF = async () => {
    console.log('Starting PDF generation...', { formData })

    try {
      const filename = `${formData["Business Name"] || "Location"}_Agreement_${new Date().toISOString().split('T')[0]}.pdf`
      
      const currentDate = formData["Agreement Date"] || new Date().toLocaleDateString()
      const paymentDetails = paymentType === "percentage" 
        ? `${formData["Revenue Share Percentage"] || "[%]"}% of all revenue generated by the Machine(s)`
        : `$${formData["Flat Fee Amount"] || "[Amount]"} per month (flat fee)`

      // Create HTML content as a string
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <title>Claw Machine Placement Agreement</title>
          <style>
            body { margin: 0; padding: 20px; font-family: Arial, sans-serif; background: white; color: #333; }
            .container { max-width: 700px; margin: 0 auto; }
            .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #2563eb; }
            .title { font-size: 24px; font-weight: bold; color: #1e40af; margin: 0 0 10px 0; }
            .subtitle { font-size: 16px; color: #64748b; margin: 0 0 20px 0; }
            .date-box { background: #f1f5f9; padding: 12px 20px; border-radius: 8px; display: inline-block; border: 1px solid #cbd5e1; }
            .parties { margin-bottom: 35px; }
            .party-boxes { display: flex; gap: 20px; margin-bottom: 20px; }
            .party-box { flex: 1; border: 2px solid #e2e8f0; padding: 20px; border-radius: 8px; background: #f8fafc; }
            .party-title { font-size: 14px; font-weight: bold; color: #1e40af; margin: 0 0 15px 0; text-align: center; padding-bottom: 8px; border-bottom: 1px solid #cbd5e1; }
            .party-info { margin: 0 0 8px 0; font-size: 12px; }
            .section { margin-bottom: 25px; padding: 20px; border-left: 4px solid #3b82f6; background: #fafbff; border-radius: 0 8px 8px 0; }
            .section-title { font-size: 14px; font-weight: bold; color: #1e40af; margin: 0 0 12px 0; }
            .section-content { font-size: 12px; line-height: 1.6; margin: 0; color: #374151; }
            .compensation { margin-bottom: 25px; padding: 25px; background: linear-gradient(135deg, #fef3c7, #fde68a); border: 2px solid #f59e0b; border-radius: 8px; }
            .compensation-title { font-size: 14px; font-weight: bold; color: #92400e; margin: 0 0 15px 0; }
            .compensation-amount { font-size: 14px; font-weight: bold; color: #92400e; background: #fffbeb; padding: 12px 15px; border-radius: 6px; text-align: center; border: 1px solid #fbbf24; margin: 10px 0; }
            .responsibilities { display: flex; gap: 20px; }
            .responsibility-box { flex: 1; background: white; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0; }
            .responsibility-title { font-size: 12px; font-weight: bold; color: #1e40af; margin: 0 0 12px 0; text-align: center; padding-bottom: 6px; border-bottom: 1px solid #e2e8f0; }
            .responsibility-list { margin: 0; padding: 0; list-style: none; }
            .responsibility-item { margin-bottom: 6px; padding-left: 15px; position: relative; font-size: 11px; }
            .responsibility-item:before { content: "•"; position: absolute; left: 0; }
            .signatures { margin-top: 40px; padding-top: 25px; border-top: 3px solid #e2e8f0; }
            .signatures-title { text-align: center; font-size: 16px; font-weight: bold; color: #1e40af; margin: 0 0 30px 0; }
            .signature-boxes { display: flex; gap: 40px; justify-content: space-between; }
            .signature-box { flex: 1; text-align: center; }
            .signature-label { font-size: 12px; font-weight: bold; color: #374151; margin: 0 0 20px 0; }
            .signature-line { border-bottom: 2px solid #1e40af; width: 200px; height: 30px; margin: 0 auto 10px auto; }
            .signature-date { font-size: 11px; color: #64748b; margin: 0; }
            .footer { text-align: center; margin-top: 30px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #9ca3af; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1 class="title">CLAW MACHINE PLACEMENT AGREEMENT</h1>
              <h2 class="subtitle">Standard 1-Year Term</h2>
              <div class="date-box">
                <strong>Effective Date: ${currentDate}</strong>
              </div>
            </div>

            <div class="parties">
              <h3 class="section-title">PARTIES TO THIS AGREEMENT</h3>
              <div class="party-boxes">
                <div class="party-box">
                  <h4 class="party-title">Claw Machine Provider</h4>
                  <p class="party-info"><strong>Name:</strong> ${formData["Provider Name"] || "[Provider Name]"}</p>
                  <p class="party-info"><strong>Address:</strong> ${formData["Provider Address"] || "[Provider Address]"}</p>
                  <p class="party-info"><strong>Contact:</strong> ${formData["Provider Contact Info"] || "[Contact Information]"}</p>
                </div>
                <div class="party-box">
                  <h4 class="party-title">Business Location Owner</h4>
                  <p class="party-info"><strong>Name:</strong> ${formData["Business Name"] || "[Business Name]"}</p>
                  <p class="party-info"><strong>Address:</strong> ${formData["Business Address"] || "[Business Address]"}</p>
                  <p class="party-info"><strong>Contact:</strong> ${formData["Business Contact Info"] || "[Contact Information]"}</p>
                </div>
              </div>
            </div>

            <div class="section">
              <h3 class="section-title">1. PURPOSE</h3>
              <p class="section-content">
                The Provider agrees to place and operate one or more claw machines (the "Machine(s)") at the Location Owner's place of business. The Location Owner agrees to host the Machine(s) in exchange for compensation as outlined in Section 3.
              </p>
            </div>

            <div class="section">
              <h3 class="section-title">2. TERM</h3>
              <p class="section-content">
                This Agreement is valid for <strong>12 months</strong>, beginning on <strong>${formData["Start Date"] || "[Start Date]"}</strong> and ending on <strong>${formData["End Date"] || "[End Date]"}</strong>, unless terminated earlier as outlined in Section 9.
              </p>
            </div>

            <div class="compensation">
              <h3 class="compensation-title">3. COMPENSATION</h3>
              <p class="section-content">
                The Provider will collect all revenue from the Machine(s) and compensate the Location Owner with:
              </p>
              <div class="compensation-amount">
                ${paymentDetails}
              </div>
              <p class="section-content">
                Payments will be made by the <strong>10th of each month</strong> for the prior month's earnings via <strong>${formData["Payment Method"] || "[Payment Method]"}</strong>.
              </p>
            </div>

            <div class="section">
              <h3 class="section-title">4. RESPONSIBILITIES</h3>
              <div class="responsibilities">
                <div class="responsibility-box">
                  <h4 class="responsibility-title">Provider Responsibilities</h4>
                  <ul class="responsibility-list">
                    <li class="responsibility-item">Owns all machines and their contents</li>
                    <li class="responsibility-item">Handles installation, restocking, and servicing</li>
                    <li class="responsibility-item">Covers all maintenance and repairs</li>
                    <li class="responsibility-item">Pays for electricity usage</li>
                    <li class="responsibility-item">Provides timely revenue reporting</li>
                  </ul>
                </div>
                <div class="responsibility-box">
                  <h4 class="responsibility-title">Location Owner Responsibilities</h4>
                  <ul class="responsibility-list">
                    <li class="responsibility-item">Provides accessible space for Machine(s)</li>
                    <li class="responsibility-item">Supplies power outlet near placement area</li>
                    <li class="responsibility-item">Maintains general cleanliness around machine</li>
                    <li class="responsibility-item">Ensures customer access during business hours</li>
                    <li class="responsibility-item">Cooperates with maintenance schedules</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="section">
              <h3 class="section-title">5. THEFT, DAMAGE & COOPERATION</h3>
              <p class="section-content">
                The Location Owner will not be held liable for theft, vandalism, or accidental damage to the Machine(s).
              </p>
              <p class="section-content">
                <strong>In the event of incidents, the Location Owner agrees to:</strong>
              </p>
              <ul class="responsibility-list">
                <li class="responsibility-item">Provide available security footage, if applicable</li>
                <li class="responsibility-item">Allow access for inspection and assessment</li>
                <li class="responsibility-item">Cooperate with law enforcement or insurance representatives</li>
                <li class="responsibility-item">Notify Provider within 24 hours of any incidents</li>
              </ul>
            </div>

            <div class="section">
              <h3 class="section-title">6. INSURANCE & LIABILITY</h3>
              <p class="section-content">
                The Provider is responsible for carrying comprehensive insurance for equipment and general liability. The Location Owner assumes no liability for injuries or damages related to the Machine(s), except in cases of gross negligence.
              </p>
            </div>

            <div class="section">
              <h3 class="section-title">7. MARKETING & SIGNAGE</h3>
              <p class="section-content">
                The Provider may display branding and promotional signage on or immediately near the Machine(s). Any additional signage in other areas of the premises must receive prior written approval from the Location Owner.
              </p>
            </div>

            <div class="section">
              <h3 class="section-title">8. RELOCATION OR REMOVAL</h3>
              <p class="section-content">
                The Provider may replace, relocate, or remove the Machine(s) with <strong>${formData["Notice Period (Hours/Days)"] || "[Notice Period]"}</strong> notice to the Location Owner. The Location Owner may request relocation of the machine within the business premises if operationally necessary.
              </p>
            </div>

            <div class="section">
              <h3 class="section-title">9. TERMINATION</h3>
              <p class="section-content">
                Either party may terminate this Agreement with <strong>30 days' written notice</strong>. Immediate termination is permitted in the event of material breach that remains uncured after 7 days' written notice.
              </p>
            </div>

            <div class="section">
              <h3 class="section-title">10. RENEWAL</h3>
              <p class="section-content">
                If neither party provides written notice of termination at least 30 days before the end date, this Agreement automatically renews for another 12-month term under the same conditions.
              </p>
            </div>

            <div class="section">
              <h3 class="section-title">11. ENTIRE AGREEMENT</h3>
              <p class="section-content">
                This document represents the complete agreement between the Parties. Any amendments must be in writing and signed by both Parties. This Agreement supersedes all prior negotiations, understandings, or agreements.
              </p>
            </div>

            <div class="signatures">
              <h3 class="signatures-title">SIGNATURES</h3>
              <div class="signature-boxes">
                <div class="signature-box">
                  <h4 class="signature-label">Claw Machine Provider</h4>
                  <div class="signature-line"></div>
                  <p class="signature-date">
                    <strong>Signature</strong><br>
                    Date: _________________
                  </p>
                </div>
                <div class="signature-box">
                  <h4 class="signature-label">Business Location Owner</h4>
                  <div class="signature-line"></div>
                  <p class="signature-date">
                    <strong>Signature</strong><br>
                    Date: _________________
                  </p>
                </div>
              </div>
            </div>

            <div class="footer">
              Generated on ${new Date().toLocaleDateString()} by ClawOps Document Creator
            </div>
          </div>
        </body>
        </html>
      `

      // Generate PDF with better configuration
      const opt = {
        margin: [10, 10, 10, 10],
        filename: filename,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { 
          scale: 2,
          useCORS: true,
          letterRendering: true,
          allowTaint: true,
          backgroundColor: '#ffffff'
        },
        jsPDF: { 
          unit: 'mm', 
          format: 'a4', 
          orientation: 'portrait'
        }
      }

      await html2pdf().from(htmlContent).set(opt).save()

      toast({
        title: "PDF Downloaded Successfully",
        description: "Your location agreement has been saved to your downloads folder.",
      })

    } catch (error) {
      console.error('PDF generation error:', error)
      toast({
        title: "PDF Generation Failed",
        description: "There was an error generating the PDF. Please try again.",
        variant: "destructive"
      })
    }
  }

  const handleClearForm = () => {
    setFormData({})
    setPaymentType("percentage")
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Location Agreement Creator</h1>
          <p className="text-muted-foreground mt-2">
            Create professional claw machine placement agreements
          </p>
        </div>
        <Button 
          variant="outline"
          onClick={handleClearForm}
        >
          Clear Form
        </Button>
      </div>

      {/* Single Card for Location Agreement */}
      <Card className="shadow-card">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Claw Machine Placement Agreement
          </CardTitle>
          <CardDescription>
            Fill in the information below to generate your professional location agreement
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {locationAgreementFields.map((field) => (
            <div key={field} className="space-y-2">
              <Label htmlFor={field.toLowerCase().replace(/\s+/g, '-')}>
                {field}
              </Label>
              <Input
                id={field.toLowerCase().replace(/\s+/g, '-')}
                placeholder={`Enter ${field.toLowerCase()}...`}
                value={formData[field] || ""}
                onChange={(e) => handleFormChange(field, e.target.value)}
              />
            </div>
          ))}

          {/* Payment Type Selection */}
          <div className="space-y-4 border-t pt-4">
            <Label className="text-base font-semibold">Payment Structure</Label>
            <RadioGroup 
              value={paymentType} 
              onValueChange={(value: "percentage" | "flat") => setPaymentType(value)}
              className="space-y-3"
            >
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="percentage" id="percentage" />
                <Label htmlFor="percentage" className="cursor-pointer">
                  Revenue Share Percentage
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="flat" id="flat" />
                <Label htmlFor="flat" className="cursor-pointer">
                  Flat Monthly Fee
                </Label>
              </div>
            </RadioGroup>

            {/* Conditional Input Fields */}
            {paymentType === "percentage" ? (
              <div className="space-y-2">
                <Label htmlFor="revenue-share">Revenue Share Percentage (%)</Label>
                <Input
                  id="revenue-share"
                  type="number"
                  min="0"
                  max="100"
                  placeholder="e.g., 50"
                  value={formData["Revenue Share Percentage"] || ""}
                  onChange={(e) => handleFormChange("Revenue Share Percentage", e.target.value)}
                />
              </div>
            ) : (
              <div className="space-y-2">
                <Label htmlFor="flat-fee">Monthly Flat Fee ($)</Label>
                <Input
                  id="flat-fee"
                  type="number"
                  min="0"
                  placeholder="e.g., 500"
                  value={formData["Flat Fee Amount"] || ""}
                  onChange={(e) => handleFormChange("Flat Fee Amount", e.target.value)}
                />
              </div>
            )}
          </div>
          
          <div className="pt-4">
            <Button 
              className="bg-gradient-primary hover:bg-primary/90 w-full"
              onClick={handleDownloadPDF}
            >
              <Download className="h-4 w-4 mr-2" />
              Generate Location Agreement PDF
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
