import { format } from "date-fns";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import {
  MapPin,
  User,
  Phone,
  Mail,
  Sparkles,
  FileText,
  DollarSign,
  Calendar,
  Building2,
  Box,
  Printer,
} from "lucide-react";
import { Location, MACHINE_TYPE_OPTIONS, CommissionSummaryRecord } from "@/hooks/useLocationsDB";
import html2pdf from "html2pdf.js";
import { useToast } from "@/hooks/use-toast";

interface LocationDetailDialogProps {
  location: Location | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function LocationDetailDialog({
  location,
  open,
  onOpenChange,
}: LocationDetailDialogProps) {
  const { toast } = useToast();
  
  if (!location) return null;

  const agreementCount = location.agreements?.length || 0;
  const commissionCount = location.commissionSummaries?.length || 0;

  const printCommissionSummary = (summary: CommissionSummaryRecord) => {
    const currentDate = new Date().toLocaleDateString();
    const periodText = `${format(new Date(summary.startDate), "MMM dd, yyyy")} - ${format(new Date(summary.endDate), "MMM dd, yyyy")}`;
    
    const content = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px; color: #333; line-height: 1.6;">
        <div style="text-align: center; margin-bottom: 40px; border-bottom: 2px solid #e5e7eb; padding-bottom: 20px;">
          <h1 style="font-size: 28px; margin: 0; color: #1f2937; font-weight: bold;">COMMISSION SUMMARY</h1>
          <p style="color: #6b7280; margin: 10px 0; font-size: 14px;">Generated on ${currentDate}</p>
        </div>

        <div style="margin-bottom: 30px;">
          <h2 style="font-size: 18px; margin: 0 0 20px 0; color: #374151; font-weight: 600;">Location Information</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 12px 0; font-weight: 600; color: #374151; width: 40%; border-bottom: 1px solid #f3f4f6;">Business Name:</td>
              <td style="padding: 12px 0; color: #1f2937; border-bottom: 1px solid #f3f4f6;">${location.name}</td>
            </tr>
            <tr>
              <td style="padding: 12px 0; font-weight: 600; color: #374151; border-bottom: 1px solid #f3f4f6;">Contact Person:</td>
              <td style="padding: 12px 0; color: #1f2937; border-bottom: 1px solid #f3f4f6;">${location.contactPerson || 'N/A'}</td>
            </tr>
            <tr>
              <td style="padding: 12px 0; font-weight: 600; color: #374151; border-bottom: 1px solid #f3f4f6;">Period:</td>
              <td style="padding: 12px 0; color: #1f2937; border-bottom: 1px solid #f3f4f6;">${periodText}</td>
            </tr>
            <tr>
              <td style="padding: 12px 0; font-weight: 600; color: #374151;">Number of Machines:</td>
              <td style="padding: 12px 0; color: #1f2937;">${summary.machineCount}</td>
            </tr>
          </table>
        </div>

        <div style="text-align: center; margin: 40px 0; padding: 30px; background: #f9fafb; border-radius: 8px;">
          <div style="margin-bottom: 25px;">
            <p style="color: #6b7280; margin: 0; font-size: 14px; text-transform: uppercase; letter-spacing: 1px;">TOTAL REVENUE</p>
            <p style="font-size: 32px; font-weight: bold; margin: 10px 0; color: #1f2937;">$${summary.totalRevenue.toFixed(2)}</p>
          </div>

          <div style="background: #dcfce7; padding: 25px; border-radius: 8px; border: 2px solid #22c55e;">
            <p style="color: #15803d; margin: 0; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; font-weight: 600;">COMMISSION PAYMENT</p>
            <p style="font-size: 36px; font-weight: bold; margin: 15px 0; color: #15803d;">$${summary.commissionAmount.toFixed(2)}</p>
          </div>
        </div>

        ${summary.notes ? `
        <div style="margin: 30px 0;">
          <h3 style="font-size: 16px; color: #374151; margin: 0 0 15px 0; font-weight: 600;">Additional Notes</h3>
          <div style="color: #4b5563; line-height: 1.6; margin: 0; padding: 20px; background: #f9fafb; border-radius: 6px; border-left: 4px solid #e5e7eb;">${summary.notes}</div>
        </div>
        ` : ''}

        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center;">
          <p style="color: #9ca3af; font-size: 12px; margin: 0;">
            This commission summary was generated by ClawOps Business Dashboard
          </p>
        </div>
      </div>
    `;

    const filename = `commission-summary-${location.name.replace(/\s+/g, '-').toLowerCase()}-${format(new Date(summary.startDate), 'yyyy-MM-dd')}.pdf`;
    
    const options = {
      margin: 0.5,
      filename: filename,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { 
        scale: 2,
        useCORS: true,
        letterRendering: true
      },
      jsPDF: { 
        unit: 'in', 
        format: 'letter', 
        orientation: 'portrait' 
      }
    };
    
    html2pdf()
      .set(options)
      .from(content)
      .save()
      .then(() => {
        toast({
          title: "PDF Generated",
          description: `Commission summary for ${location.name} downloaded.`,
        });
      })
      .catch((error: any) => {
        console.error('PDF generation error:', error);
        toast({
          title: "PDF Generation Failed",
          description: "There was an error generating the PDF.",
          variant: "destructive"
        });
      });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <div className="p-2 rounded-lg bg-primary/10">
              <MapPin className="h-5 w-5 text-primary" />
            </div>
            <div>
              <span>{location.name}</span>
              <Badge
                variant={location.isActive ? "default" : "secondary"}
                className="ml-3"
              >
                {location.isActive ? "Active" : "Inactive"}
              </Badge>
            </div>
          </DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="details" className="flex-1 flex flex-col min-h-0">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="details" className="flex items-center gap-2">
              <Building2 className="h-4 w-4" />
              Details
            </TabsTrigger>
            <TabsTrigger value="agreements" className="flex items-center gap-2">
              <FileText className="h-4 w-4" />
              Agreements
              {agreementCount > 0 && (
                <Badge variant="secondary" className="ml-1 h-5 px-1.5">
                  {agreementCount}
                </Badge>
              )}
            </TabsTrigger>
            <TabsTrigger value="commissions" className="flex items-center gap-2">
              <DollarSign className="h-4 w-4" />
              Commissions
              {commissionCount > 0 && (
                <Badge variant="secondary" className="ml-1 h-5 px-1.5">
                  {commissionCount}
                </Badge>
              )}
            </TabsTrigger>
          </TabsList>

          <ScrollArea className="flex-1 mt-4">
            {/* Details Tab */}
            <TabsContent value="details" className="mt-0 space-y-4">
              <Card>
                <CardContent className="pt-4 space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-muted-foreground flex items-center gap-1">
                        <MapPin className="h-3 w-3" /> Address
                      </p>
                      <p className="font-medium">{location.address || "—"}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground flex items-center gap-1">
                        <User className="h-3 w-3" /> Contact Person
                      </p>
                      <p className="font-medium">{location.contactPerson || "—"}</p>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-muted-foreground flex items-center gap-1">
                        <Phone className="h-3 w-3" /> Phone
                      </p>
                      <p className="font-medium">{location.contactPhone || "—"}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground flex items-center gap-1">
                        <Mail className="h-3 w-3" /> Email
                      </p>
                      <p className="font-medium">{location.contactEmail || "—"}</p>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-muted-foreground flex items-center gap-1">
                        <Sparkles className="h-3 w-3" /> Total Machines
                      </p>
                      <p className="font-medium">{location.machineCount}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">Commission Rate</p>
                      <p className="font-medium">
                        {location.commissionRate > 0
                          ? `${location.commissionRate}%`
                          : "—"}
                      </p>
                    </div>
                  </div>

                  {/* Machine Types Breakdown */}
                  {location.machines && location.machines.length > 0 && (
                    <div>
                      <p className="text-sm text-muted-foreground flex items-center gap-1 mb-2">
                        <Box className="h-3 w-3" /> Machine Breakdown
                      </p>
                      <div className="flex flex-wrap gap-2">
                        {location.machines.map((machine, index) => (
                          <Badge key={index} variant="secondary" className="text-xs">
                            {machine.label}: {machine.count}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  )}

                  {location.notes && (
                    <div>
                      <p className="text-sm text-muted-foreground">Notes</p>
                      <p className="font-medium">{location.notes}</p>
                    </div>
                  )}

                  <div className="pt-2 border-t">
                    <p className="text-xs text-muted-foreground">
                      Created: {format(new Date(location.createdAt), "MMM d, yyyy")}
                    </p>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            {/* Agreements Tab */}
            <TabsContent value="agreements" className="mt-0 space-y-3">
              {agreementCount === 0 ? (
                <div className="text-center py-12">
                  <div className="w-16 h-16 rounded-full bg-muted/50 flex items-center justify-center mx-auto mb-3">
                    <FileText className="h-8 w-8 text-muted-foreground/50" />
                  </div>
                  <p className="text-muted-foreground font-medium">No agreements yet</p>
                  <p className="text-sm text-muted-foreground/70 mt-1">
                    Generate an agreement from the Documents page
                  </p>
                </div>
              ) : (
                location.agreements.map((agreement) => (
                  <Card key={agreement.id} className="hover:shadow-md transition-shadow">
                    <CardContent className="pt-4">
                      <div className="flex items-start justify-between mb-3">
                        <div>
                          <p className="font-medium">{agreement.providerName}</p>
                          <p className="text-sm text-muted-foreground">
                            {agreement.providerAddress}
                          </p>
                        </div>
                        <Badge variant="outline">
                          {agreement.paymentType === "percentage"
                            ? `${agreement.revenueSharePercentage}% Share`
                            : `$${agreement.flatFeeAmount?.toFixed(2)} Flat`}
                        </Badge>
                      </div>

                      <div className="grid grid-cols-3 gap-3 text-sm">
                        <div>
                          <p className="text-muted-foreground flex items-center gap-1">
                            <Calendar className="h-3 w-3" /> Agreement Date
                          </p>
                          <p className="font-medium">
                            {format(new Date(agreement.agreementDate), "MMM d, yyyy")}
                          </p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">Start Date</p>
                          <p className="font-medium">
                            {format(new Date(agreement.startDate), "MMM d, yyyy")}
                          </p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">End Date</p>
                          <p className="font-medium">
                            {format(new Date(agreement.endDate), "MMM d, yyyy")}
                          </p>
                        </div>
                      </div>

                      <div className="mt-3 pt-3 border-t flex justify-between text-xs text-muted-foreground">
                        <span>Payment: {agreement.paymentMethod}</span>
                        <span>Notice: {agreement.noticePeriod}</span>
                      </div>
                    </CardContent>
                  </Card>
                ))
              )}
            </TabsContent>

            {/* Commission Summaries Tab */}
            <TabsContent value="commissions" className="mt-0 space-y-3">
              {commissionCount === 0 ? (
                <div className="text-center py-12">
                  <div className="w-16 h-16 rounded-full bg-muted/50 flex items-center justify-center mx-auto mb-3">
                    <DollarSign className="h-8 w-8 text-muted-foreground/50" />
                  </div>
                  <p className="text-muted-foreground font-medium">
                    No commission summaries yet
                  </p>
                  <p className="text-sm text-muted-foreground/70 mt-1">
                    Generate a summary from the Commission Summary page
                  </p>
                </div>
              ) : (
                location.commissionSummaries.map((summary) => (
                  <Card key={summary.id} className="hover:shadow-md transition-shadow">
                    <CardContent className="pt-4">
                      <div className="flex items-start justify-between mb-3">
                        <div>
                          <p className="font-medium flex items-center gap-2">
                            <Calendar className="h-4 w-4 text-muted-foreground" />
                            {format(new Date(summary.startDate), "MMM d")} -{" "}
                            {format(new Date(summary.endDate), "MMM d, yyyy")}
                          </p>
                        </div>
                        <div className="flex items-center gap-2">
                          <Badge className="bg-primary/20 text-primary hover:bg-primary/30">
                            ${summary.commissionAmount.toFixed(2)}
                          </Badge>
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => printCommissionSummary(summary)}
                            className="h-7 px-2"
                          >
                            <Printer className="h-3.5 w-3.5 mr-1" />
                            Print
                          </Button>
                        </div>
                      </div>

                      <div className="grid grid-cols-3 gap-3 text-sm">
                        <div>
                          <p className="text-muted-foreground">Total Revenue</p>
                          <p className="font-medium text-lg">
                            ${summary.totalRevenue.toFixed(2)}
                          </p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">Commission</p>
                          <p className="font-medium">
                            {summary.commissionPercentage}%
                          </p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">Machines</p>
                          <p className="font-medium">{summary.machineCount}</p>
                        </div>
                      </div>

                      {summary.notes && (
                        <div className="mt-3 pt-3 border-t">
                          <p className="text-xs text-muted-foreground">
                            Notes: {summary.notes}
                          </p>
                        </div>
                      )}

                      <p className="text-xs text-muted-foreground mt-2">
                        Generated:{" "}
                        {format(new Date(summary.createdAt), "MMM d, yyyy 'at' h:mm a")}
                      </p>
                    </CardContent>
                  </Card>
                ))
              )}
            </TabsContent>
          </ScrollArea>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
